# hyprlauncher.conf - setup básico e útil

general:
  grab_focus = true

cache:
  enabled = true

finders:
  # finder padrão: apps .desktop
  default_finder       = desktop

  # digita "." antes pra pegar unicode/emoji
  unicode_prefix       = .

  # digita "=" pra fazer conta e copiar o resultado
  math_prefix          = =

  # se você usar uwsm, pode setar isso aqui, senão deixa vazio
  desktop_launch_prefix = ""

  # mostra ícones dos apps
  desktop_icons        = true

