# arete.nvim EF theme: ef-atlantis
foreground #bfcccf
background #1a143e
selection_foreground #bfcccf
selection_background #32446b
cursor #baa1ab
cursor_text_color #1a143e

color0 #1a143e
color1 #ef656a
color2 #1fa526
color3 #c48502
color4 #379cf6
color5 #d590af
color6 #4fb0cf
color7 #7f8385
color8 #3a4661
color9 #f47360
color10 #00a972
color11 #e6832f
color12 #6a88ff
color13 #af9ef2
color14 #3dc0b0
color15 #bfcccf

