# arete.nvim EF theme: ef-autumn
foreground #cfbcba
background #0f0e06
selection_foreground #cfbcba
selection_background #3f1324
cursor #ffaa33
cursor_text_color #0f0e06

color0 black
color1 #ff7a7f
color2 #2fa526
color3 #c48702
color4 #6a88ff
color5 #d570af
color6 #4fb0cf
color7 gray65
color8 gray35
color9 #f06a3f
color10 #64aa0f
color11 #d0730f
color12 #029fff
color13 #af8aff
color14 #6fafff
color15 white

