# arete.nvim EF theme: ef-arbutus
foreground #393330
background #ffead8
selection_foreground #393330
selection_background #dbe0c0
cursor #208f10
cursor_text_color #ffead8

color0 black
color1 #aa184f
color2 #007000
color3 #906200
color4 #5f55df
color5 #a23ea4
color6 #3f69af
color7 gray65
color8 gray35
color9 #b20f00
color10 #557000
color11 #b44405
color12 #265fbf
color13 #6448ca
color14 #0f7688
color15 white

