# arete.nvim EF theme: ef-cyprus
foreground #242521
background #fcf7ef
selection_foreground #242521
selection_background #e0e7e5
cursor #007f00
cursor_text_color #fcf7ef

color0 black
color1 #9f0d0f
color2 #006f00
color3 #a7601f
color4 #444fcf
color5 #9a456f
color6 #3f6faf
color7 gray65
color8 gray35
color9 #dd0020
color10 #557400
color11 #bf4400
color12 #065fbf
color13 #8448aa
color14 #007a9f
color15 white

