# arete.nvim EF theme: ef-cherie
foreground #d3cfcf
background #190a0f
selection_foreground #d3cfcf
selection_background #232f3f
cursor #ff5aaf
cursor_text_color #190a0f

color0 black
color1 #ff7359
color2 #60b444
color3 #e5b76f
color4 #8fa5f6
color5 #ef80bf
color6 #8fbaef
color7 gray65
color8 gray35
color9 #ff656f
color10 #60bf88
color11 #ea9955
color12 #a897ef
color13 #df7fff
color14 #8fcfdf
color15 white

