# arete.nvim EF theme: ef-deuteranopia-dark
foreground #ddddee
background #000a1f
selection_foreground #ddddee
selection_background #223848
cursor #ffff00
cursor_text_color #000a1f

color0 black
color1 #cf7a7a
color2 #3faa26
color3 #aa9f32
color4 #6a9fff
color5 #b379bf
color6 #5faaef
color7 gray65
color8 gray35
color9 #e47360
color10 #7aad0f
color11 #cfaf00
color12 #009fff
color13 #9f95ff
color14 #0db0ff
color15 white

