# arete.nvim EF theme: ef-dark
foreground #d0d0d0
background #000000
selection_foreground #d0d0d0
selection_background #2a234a
cursor #ff76ff
cursor_text_color #000000

color0 black
color1 #ef6560
color2 #0faa26
color3 #bf9032
color4 #3f95f6
color5 #d369af
color6 #6fafff
color7 gray65
color8 gray35
color9 #f47360
color10 #6aad0f
color11 #df8a5a
color12 #029fff
color13 #af85ff
color14 #1dbfcf
color15 white

