# arete.nvim EF theme: ef-day
foreground #584141
background #fff5ea
selection_foreground #584141
selection_background #f0d2df
cursor #cf1f00
cursor_text_color #fff5ea

color0 black
color1 #ba2d2f
color2 #007a0a
color3 #a45a22
color4 #375cc6
color5 #ca3e54
color6 #3f60af
color7 gray65
color8 gray35
color9 #ce3f00
color10 #5f7200
color11 #aa4f30
color12 #5f5fdf
color13 #8448aa
color14 #0f7b8f
color15 white

