# arete.nvim EF theme: ef-duo-dark
foreground #d0d0d0
background #070019
selection_foreground #d0d0d0
selection_background #042a50
cursor #ef6f11
cursor_text_color #070019

color0 black
color1 #ef656a
color2 #50a22f
color3 #c48702
color4 #6f80ff
color5 #d369af
color6 #5faaef
color7 gray65
color8 gray35
color9 #f47360
color10 #00b982
color11 #d0730f
color12 #029fff
color13 #af85ff
color14 #0dafdf
color15 white

