# arete.nvim EF theme: ef-duo-light
foreground #222222
background #fff8f0
selection_foreground #222222
selection_background #caeafa
cursor #1144ff
cursor_text_color #fff8f0

color0 black
color1 #c04440
color2 #217a3c
color3 #8a5d00
color4 #4250ef
color5 #ba35af
color6 #3f70a0
color7 gray65
color8 gray35
color9 #dd1100
color10 #008058
color11 #9f4a00
color12 #065fff
color13 #6052cf
color14 #1f77bb
color15 white

