# arete.nvim EF theme: ef-dream
foreground #efd5c5
background #232025
selection_foreground #efd5c5
selection_background #544a50
cursor #f3c09a
cursor_text_color #232025

color0 black
color1 #ff6f6f
color2 #7fce5f
color3 #c0b24f
color4 #80aadf
color5 #ffaacf
color6 #6fb3c0
color7 gray65
color8 gray35
color9 #ff7a5f
color10 #3fc489
color11 #d09950
color12 #12b4ff
color13 #d0b0ff
color14 #65c5a8
color15 white

