# arete.nvim EF theme: ef-elea-dark
foreground #eaf2ef
background #222524
selection_foreground #eaf2ef
selection_background #543040
cursor #ef7fa8
cursor_text_color #222524

color0 black
color1 #ff656a
color2 #7fc87f
color3 #cac85f
color4 #57aff6
color5 #f59acf
color6 #7fcfdf
color7 gray65
color8 gray35
color9 #ff7a5f
color10 #50cf89
color11 #e0b02f
color12 #78afff
color13 #cfaaff
color14 #60d5c2
color15 white

