# arete.nvim EF theme: ef-elea-light
foreground #221321
background #edf5e2
selection_foreground #221321
selection_background #d9d2ef
cursor #770080
cursor_text_color #edf5e2

color0 black
color1 #c3303a
color2 #00601f
color3 #9a501f
color4 #375cc6
color5 #80308f
color6 #3f6faf
color7 gray65
color8 gray35
color9 #d00000
color10 #007047
color11 #88541f
color12 #444fcf
color13 #5032aa
color14 #00677f
color15 white

