# arete.nvim EF theme: ef-frost
foreground #232323
background #fcffff
selection_foreground #232323
selection_background #d4eaf3
cursor #0055bb
cursor_text_color #fcffff

color0 black
color1 #c42d2f
color2 #008a00
color3 #aa6100
color4 #4244ef
color5 #aa44c5
color6 #3a6dd2
color7 gray65
color8 gray35
color9 #cf2f4f
color10 #00845f
color11 #996c4f
color12 #065fff
color13 #7f5ae0
color14 #1f6fbf
color15 white

