# arete.nvim EF theme: ef-kassio
foreground #201f36
background #fff7f7
selection_foreground #201f36
selection_background #dfe4f4
cursor #d06f30
cursor_text_color #fff7f7

color0 black
color1 #b00234
color2 #217a3c
color3 #9a6012
color4 #3c3bbe
color5 #a01f64
color6 #2f5f9f
color7 gray65
color8 gray35
color9 #e00033
color10 #4a7d00
color11 #a04646
color12 #4250ef
color13 #7022bf
color14 #1077ab
color15 white

