# arete.nvim EF theme: ef-melissa-dark
foreground #e8e4b1
background #352718
selection_foreground #e8e4b1
selection_background #443a4f
cursor #f9cf7a
cursor_text_color #352718

color0 black
color1 #ff7f7f
color2 #6fd560
color3 #e4b53f
color4 #57aff6
color5 #fa90aa
color6 #6fcad0
color7 gray65
color8 gray35
color9 #ff8f98
color10 #65d590
color11 #e7a06f
color12 #98bfff
color13 #c6a2fe
color14 #70e0cf
color15 white

