# arete.nvim EF theme: ef-melissa-light
foreground #484431
background #fff6d8
selection_foreground #484431
selection_background #f0d4d8
cursor #a07f00
cursor_text_color #fff6d8

color0 black
color1 #ba2d2f
color2 #007a0a
color3 #a26310
color4 #375cc6
color5 #aa3e74
color6 #3f60af
color7 gray65
color8 gray35
color9 #c74400
color10 #5a7400
color11 #ba5205
color12 #5f5fdf
color13 #6448ca
color14 #0f708a
color15 white

