# arete.nvim EF theme: ef-maris-dark
foreground #eaedef
background #131c2b
selection_foreground #eaedef
selection_background #183c65
cursor #8fdfff
cursor_text_color #131c2b

color0 black
color1 #ff6f6f
color2 #41bf4f
color3 #d0d24f
color4 #57b0ff
color5 #f59acf
color6 #2fd0db
color7 gray65
color8 gray35
color9 #ff7788
color10 #7fce5f
color11 #f0c060
color12 #70a0ff
color13 #cf90ff
color14 #65d5a8
color15 white

