# arete.nvim EF theme: ef-maris-light
foreground #151a27
background #edf4f8
selection_foreground #151a27
selection_background #c8dcff
cursor #036f99
cursor_text_color #edf4f8

color0 black
color1 #b02440
color2 #007010
color3 #805a1f
color4 #444fcf
color5 #80308f
color6 #1f66af
color7 gray65
color8 gray35
color9 #d00000
color10 #007047
color11 #8b4400
color12 #003faf
color13 #5f2fba
color14 #006f70
color15 white

