# arete.nvim EF theme: ef-night
foreground #afbcbf
background #000e17
selection_foreground #afbcbf
selection_background #253146
cursor #00ccff
cursor_text_color #000e17

color0 black
color1 #ef656a
color2 #1fa526
color3 #c48502
color4 #379cf6
color5 #d570af
color6 #4fb0cf
color7 gray65
color8 gray35
color9 #f47360
color10 #50a22f
color11 #e6832f
color12 #6a88ff
color13 #af8aff
color14 #3dc0b0
color15 white

