# arete.nvim EF theme: ef-owl
foreground #d0d0d0
background #292c2f
selection_foreground #d0d0d0
selection_background #404f66
cursor #afe6ef
cursor_text_color #292c2f

color0 black
color1 #d67869
color2 #70bb70
color3 #c09f6f
color4 #80a4e0
color5 #e5a0ea
color6 #99bfd0
color7 gray65
color8 gray35
color9 #df885f
color10 #98c06f
color11 #cf9f90
color12 #72aff0
color13 #cfa0e8
color14 #7ac0b9
color15 white

