# arete.nvim EF theme: ef-orange
foreground #6c4631
background #ffedc9
selection_foreground #6c4631
selection_background #eeb48f
cursor #cf5f00
cursor_text_color #ffedc9

color0 #6c4631
color1 #ba2d2f
color2 #007a0a
color3 #a05a22
color4 #375cc6
color5 #ba3e54
color6 #467080
color7 #c9b088
color8 #6f6a70
color9 #c13f00
color10 #2f783f
color11 #b05115
color12 #5f50df
color13 #8448aa
color14 #0f738f
color15 #ffedc9

