# arete.nvim EF theme: ef-reverie
foreground #4f204f
background #f3eddf
selection_foreground #4f204f
selection_background #e0d0ba
cursor #9d5744
cursor_text_color #f3eddf

color0 black
color1 #ba2d2f
color2 #5a7400
color3 #87591f
color4 #5059c0
color5 #9f4e74
color6 #3060af
color7 gray65
color8 gray35
color9 #b21f00
color10 #008250
color11 #a05900
color12 #265fbf
color13 #7755b4
color14 #0b6e8a
color15 white

