# arete.nvim EF theme: ef-rosa
foreground #e4d3e1
background #322023
selection_foreground #e4d3e1
selection_background #45524a
cursor #ef607a
cursor_text_color #322023

color0 black
color1 #ff707f
color2 #5fbb5f
color3 #e4c53f
color4 #57aff6
color5 #ffb2d6
color6 #5fc0dc
color7 gray65
color8 gray35
color9 #ff7f5f
color10 #8ad05a
color11 #f2a85f
color12 #78b2ff
color13 #cfb1ff
color14 #80dfbf
color15 white

