# arete.nvim EF theme: ef-summer
foreground #4f4073
background #fff2f3
selection_foreground #4f4073
selection_background #eecfff
cursor #cf0090
cursor_text_color #fff2f3

color0 black
color1 #d50f7f
color2 #217a3c
color3 #a45f22
color4 #5250ef
color5 #ba35af
color6 #1f6fbf
color7 gray65
color8 gray35
color9 #e00033
color10 #4a7d00
color11 #b6532f
color12 #065fff
color13 #8e44f3
color14 #0f7b8f
color15 white

