# arete.nvim EF theme: ef-symbiosis
foreground #d0d0d0
background #130911
selection_foreground #d0d0d0
selection_background #3f2f40
cursor #f0af7f
cursor_text_color #130911

color0 black
color1 #fe5a7a
color2 #0faa26
color3 #bf9032
color4 #6a9fff
color5 #d369af
color6 #4fbaef
color7 gray65
color8 gray35
color9 #ff7355
color10 #6aad0f
color11 #df8a5a
color12 #029fff
color13 #af85ff
color14 #1dbfcf
color15 white

