# arete.nvim EF theme: ef-trio-light
foreground #4f3363
background #f8f5ff
selection_foreground #4f3363
selection_background #eed0ff
cursor #4f45ff
cursor_text_color #f8f5ff

color0 black
color1 #c01f5f
color2 #057800
color3 #a45f22
color4 #5165e4
color5 #ad45ba
color6 #1f6fbf
color7 gray65
color8 gray35
color9 #d03033
color10 #4f7d0f
color11 #b8532f
color12 #065fbf
color13 #705ae3
color14 #0f7a9d
color15 white

