# arete.nvim EF theme: ef-tritanopia-light
foreground #1a1a1a
background #fff9f9
selection_foreground #1a1a1a
selection_background #dadadf
cursor #bb0000
cursor_text_color #fff9f9

color0 black
color1 #c50f4f
color2 #217a3c
color3 #805d00
color4 #4250ef
color5 #aa357f
color6 #2070af
color7 gray65
color8 gray35
color9 #dd0000
color10 #4a7d00
color11 #965000
color12 #065fff
color13 #af40af
color14 #007faa
color15 white

