# arete.nvim EF theme: ef-tritanopia-dark
foreground #dfd0d5
background #15050f
selection_foreground #dfd0d5
selection_background #293140
cursor #fd3333
cursor_text_color #15050f

color0 black
color1 #d24f7f
color2 #2fa526
color3 #c48702
color4 #6a88ff
color5 #b0648f
color6 #3fafcf
color7 gray65
color8 gray35
color9 #df4f4f
color10 #64aa0f
color11 #d0730f
color12 #029fff
color13 #a6699f
color14 #4fafaf
color15 white

