# arete.nvim EF theme: ef-trio-dark
foreground #d8cfd5
background #160f0f
selection_foreground #d8cfd5
selection_background #16304f
cursor #ff99ff
cursor_text_color #160f0f

color0 black
color1 #ff85aa
color2 #60b444
color3 #d4a052
color4 #8895ff
color5 #d37faf
color6 #8fbaff
color7 gray65
color8 gray35
color9 #ff7560
color10 #a0c27f
color11 #ef926f
color12 #72afff
color13 #a698ef
color14 #8fcfdf
color15 white

