# arete.nvim EF theme: ef-winter
foreground #b8c6d5
background #0f0b15
selection_foreground #b8c6d5
selection_background #342464
cursor #ff6ff0
cursor_text_color #0f0b15

color0 black
color1 #ff6a7a
color2 #29a444
color3 #b58a52
color4 #6a9fff
color5 #d369af
color6 #4fbaef
color7 gray65
color8 gray35
color9 #ef6560
color10 #6aad0f
color11 #d1803f
color12 #029fff
color13 #af85ea
color14 #35afbf
color15 white

