# Só roda isso em sessões interativas
if status is-interactive

    # zoxide
    zoxide init fish | source
    function cd
        z $argv
    end

    # Pokémon colorido na abertura
    function fish_greeting
        fastfetch --config tiny
    end

    # Aliases com lsd
    alias ls="lsd --icon always --group-dirs first"
    alias ll="lsd -l --icon always --group-dirs first"
    alias la="lsd -la --icon always --group-dirs first"
    alias lt="lsd --tree --icon always"

    # Aliases úteis
    alias vim="nvim"
    alias n="nvim"
    alias py="python"
    alias yt="omarchy-launch-webapp https://music.youtube.com"
    alias click="omarchy-launch-webapp https://app.clickup.com"
    alias watz="omarchy-launch-webapp https://web.whatsapp.com" # Starship prompt
    starship init fish | source
end

# PATH do cargo
fish_add_path ~/.cargo/bin

echo 'set -gx PATH $HOME/.local/share/omarchy/bin $PATH' >>~/.config/fish/config.fish
# Editor padrão
set -gx EDITOR nvim
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
set -gx PATH $HOME/.local/share/omarchy/bin $PATH
